name: maps_launcher
description: Simple Flutter package to open the maps application (or browser) on all platforms.
version: 1.2.0
homepage: https://github.com/Pikaju/FlutterMapsLauncher

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ">=5.3.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter