name: maps_launcher
description: Simple Flutter package to open the maps application on iOS and Android.
version: 1.0.1
author: Julien Scholz <julienscholzo@hotmail.de>
homepage: https://github.com/Pikaju/FlutterMapsLauncher

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter